name: PVS-Studio CMake Analysis

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository URL"
        required: true
        default: "https://github.com/Vita3K/Vita3K"
      branch:
        description: "Branch name"
        required: true
        default: "main"

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: pvsstudio/pvs-studio:latest
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
        path: src

    - name: Set up build environment (ubuntu-22.04)
      run: |
          sudo add-apt-repository -y ppa:mhier/libboost-latest
          sudo add-apt-repository universe
          sudo apt update
          sudo apt -y install ccache libboost-filesystem1.83-dev libboost-program-options1.83-dev libboost-system1.83-dev libgtk-3-dev libsdl2-dev ninja-build libfuse2

    - name: Set up SDL 2.30.9 (ubuntu-22.04)
      run: |
          SDL2VER=2.30.9
          if [[ ! -e ~/.ccache ]]; then
            mkdir ~/.ccache
          fi  
          cd ~/.ccache
          if [[ ! -e SDL2-${SDL2VER} ]]; then
            curl -sLO https://libsdl.org/release/SDL2-${SDL2VER}.tar.gz
            tar -xzf SDL2-${SDL2VER}.tar.gz
            cd SDL2-${SDL2VER}
            ./configure --prefix=/usr/local
            make && cd ../
            rm SDL2-${SDL2VER}.tar.gz
          fi
          sudo make -C SDL2-${SDL2VER} install


    - name: Configure project with CMake
      run: |
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --preset linux-ninja-clang
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --build build/linux-ninja-clang --config Release

    - name: Run PVS-Studio analysis
      run: |
        cd build/linux-ninja-clang
        pvs-studio-analyzer analyze \
          --compilation-database compile_commands.json \
          --output-file pvs.log \
          -j $(nproc) \
          --disableLicenseExpirationCheck

        plog-converter -a GA:1,2 -t html -o report.html pvs.log

    - name: Upload PVS-Studio report
      uses: actions/upload-artifact@v4
      with:
        name: PVS-Report
        path: build/linux-ninja-clang/report.html