name: PVS-Studio CMake Analysis

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository URL"
        required: true
        default: "Vita3K/Vita3K"
      branch:
        description: "Branch name"
        required: true
        default: "master"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Install PVS-Studio
      run: |
        wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
        sudo apt-get update
        sudo apt-get install -y pvs-studio

    - name: Configure license
      run: |
        pvs-studio-analyzer credentials -o $PVS_KEY $PVS_USERNAME
      env:
        PVS_USERNAME: ${{ secrets.PVS_USERNAME }}
        PVS_KEY: ${{ secrets.PVS_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
        path: src
        fetch-depth: 0
        submodules: recursive

    - name: Set up build environment (ubuntu-22.04)
      run: |
          sudo add-apt-repository -y ppa:mhier/libboost-latest
          sudo add-apt-repository universe
          sudo apt update
          sudo apt -y install ccache libboost-filesystem1.83-dev libboost-program-options1.83-dev libboost-system1.83-dev libgtk-3-dev libsdl2-dev ninja-build libfuse2

    - name: Set up SDL 2.30.9 (ubuntu-22.04)
      run: |
          SDL2VER=2.30.9
          if [[ ! -e ~/.ccache ]]; then
            mkdir ~/.ccache
          fi  
          cd ~/.ccache
          if [[ ! -e SDL2-${SDL2VER} ]]; then
            curl -sLO https://libsdl.org/release/SDL2-${SDL2VER}.tar.gz
            tar -xzf SDL2-${SDL2VER}.tar.gz
            cd SDL2-${SDL2VER}
            ./configure --prefix=/usr/local
            make && cd ../
            rm SDL2-${SDL2VER}.tar.gz
          fi
          sudo make -C SDL2-${SDL2VER} install


    - name: Configure project with CMake
      run: |
        cd src
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --preset linux-ninja-clang
        cmake --build build/linux-ninja-clang 

    - name: Run PVS-Studio analysis
      run: |
        cd src/build/linux-ninja-clang
        pvs-studio-analyzer analyze \
          --compilation-database compile_commands.json \
          --output-file pvs.log \
          -j $(nproc) \
          --disableLicenseExpirationCheck

        plog-converter -a GA:1,2 -t html -o report.html pvs.log

    - name: Upload PVS-Studio report
      uses: actions/upload-artifact@v4
      with:
        name: PVS-Report
        path: build/linux-ninja-clang/report.html